# Generated by Django 2.2.2 on 2019-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('zone_id', models.FloatField(blank=True, null=True)),
                ('stop_lon', models.FloatField(blank=True, null=True)),
                ('stop_id', models.TextField(blank=True, null=True)),
                ('stop_name', models.TextField(blank=True, null=True)),
                ('location_type', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('c1', models.IntegerField(primary_key=True, serialize=False)),
                ('c2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': True,
            },
        ),
    ]
