# Generated by Django 2.2.2 on 2019-07-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='routesperstop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stops',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stoptimes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'managed': False},
        ),
    ]
