# Generated by Django 2.2.2 on 2019-06-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190625_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stops',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stoptimes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'managed': True},
        ),
    ]
