# Generated by Django 2.2.2 on 2019-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190625_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apikeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ApiKeys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RestApiKey',
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stops',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stoptimes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'managed': False},
        ),
    ]
